services:
  - type: web
    name: ca-phe-viet
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_KEY
        value: hv2026admin
      - key: ADMIN_EMAIL
        value: minhhoangle2909@gmail.com
